### ISSUE TITLE
Certain URIs in EQ pattern confused by axiom printing

### ISSUE THREAD

**Issue by debuos512** [bio-ontology-research-group/opa2vec#10]
The axiom printer for the ontology corpus surrounds sub-clauses with parentheses, which I think will be included in the word2vec word tokens representing certain IRIs. This problem applies to the EQ pattern e.g. 

<http://phenomebrowser.net/plant-phenotype.owl#PPNET:2095> EquivalentTo <http://purl.obolibrary.org/obo/BFO_0000051> some  (<http://purl.obolibrary.org/obo/PO_0000003> and (<http://phenomebrowser.net/#has-quality> some <http://purl.obolibrary.org/obo/PATO_0001154>))

Here e.g. "(<http://purl.obolibrary.org/obo/PO_0000003>" will be one token. I think that these should be stripped from the output?

**Comment by ChaseWLW** [comment]
Similarly, there are comma characters that should be stripped. For example:
EquivalentClasses: <http://purl.obolibrary.org/obo/HP_0003109>, <http://purl.obolibrary.org/obo/HP_0012365>, <http://purl.obolibrary.org/obo/MP_0002901>, <http://purl.obolibrary.org/obo/MP_0002902>

**Comment by fzohrasmaili** [comment]
Can you retry with the updated version  of ProcessOntology.groovy ? It basically ignores parentheses and commas when printing the logical axioms.

**Comment by ChaseWLW** [comment]
There is no axioms.lst from the new version. I think '(' and ')' are special symbols and need to be escaped in java regex. Please see https://stackoverflow.com/questions/30839697/java-util-regex-patternsyntaxexception-unmatched-closing-during-string-sp

**Comment by fzohrasmaili** [comment]
Thanks Chase. The parentheses needed to be escaped as you mentioned.
