### ISSUE TITLE
How are GO terms being converted to vectors? 

### ISSUE THREAD

**Issue by datduong** [bio-ontology-research-group/opa2vec#16]
I would like to understand specifically how are the GO terms get converted into vectors. Pleaese correct me if I am understanding the paper incorrectly. 

From the paper, I understand that the method uses phrases like `GO1 is subclass of GO2`. 
Then, each word in the phrase `GO1 is subclass of GO2` is converted into a vector by w2v model. So I assume that you would have the vector `vector(GO1)`, `vector(is)`, `vector(subclass)`, `vector(of)`, `vector(GO2)`. 

However, the GO1 and GO2 will have some long descriptions. Where are the descriptions being used here? 

Thanks.

**Comment by fzohrasmaili** [comment]
Hello,
The  text corpus we use includes both the logical axioms (e.g. GO1 SubclassOf GO2) and the metadata of the ontology which includes the descriptions, labels, synonyms etc. Therefore, when we apply word2vec on this corpus, the obtained vector of term GO1 for example will encode both the information contained in the logical axioms related to this term and the information in the metadata of the term such as the descriptions.

Hope this clarifies your questions, 
Please let us know if you have any other concerns.

**Comment by datduong** [comment]
Thanks for the reply. Just to clarify, when you say one sample is (GO1 SubclassOf GO2), do you mean that: (definition of GO1 is SubclassOf definition of GO2)? Would it be possible to see a concrete example of what one single input is? Thanks for your help on this.

**Comment by fzohrasmaili** [comment]
An example of the ontology corpus would be:

**HP_000253 _SubclassOf_ HP_000534
HP_000253 _hasDescription_ increased height of the central portion of the  eyebrow, forming a crescent, semicircular, or inverted U shape**

(I am using here the short format just as an illustration, but the actual corpus will actually include the full URIs)

**HP_000253 _SubclassOf_ HP_000534** is an example of a logical axiom.
**HP_000253 _hasDescription_ increased height of the central portion of the  eyebrow, forming a crescent, semicircular, or inverted U shape** is an example of a metadata description.

All logical axioms and metadata of the ontology will be included in the text corpus.

I hope this clarifies a bit more,

**Comment by datduong** [comment]
I understand what is being fed into the w2v model now. Thanks for your help.
