### ISSUE TITLE
How can I get "association file" from my owl file?

### ISSUE THREAD

**Issue by CNwangbin** [bio-ontology-research-group/opa2vec#19]
![image](https://user-images.githubusercontent.com/87804802/190548379-0800f9a3-fc0b-46d6-91ba-8b4aa152afc2.png)
Sorry, I don't know how to generate association file from my owl file.Is there any examples?

**Comment by leechuck** [comment]
You would have to create it yourself, following the style of the example file, https://github.com/bio-ontology-research-group/opa2vec/blob/master/SampleAssociationFile.lst.

However, you may want to check the OPA2Vec implementation in mOWL (https://github.com/bio-ontology-research-group/mowl/) for a more robust implementation of the algorithm.

**Comment by CNwangbin** [comment]
OK,thanks.Is that DL2Vec refer as Onto2vec?
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Robert&nbsp;Hoehndorf"; 
Date: 2022年9月16日(星期五) 下午2:41
To: "bio-ontology-research-group/opa2vec"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [bio-ontology-research-group/opa2vec] How can I get &quot;association file&quot; from my owl file? (Issue #19)

&nbsp;


 
You would have to create it yourself, following the style of the example file, https://github.com/bio-ontology-research-group/opa2vec/blob/master/SampleAssociationFile.lst.
 
However, you may want to check the OPA2Vec implementation in mOWL (https://github.com/bio-ontology-research-group/mowl/) for a more robust implementation of the algorithm.

**Comment by ferzcam** [comment]
Hi, in case you are planning to use mOWL to implement OPA2Vec, you may want to look at this [example](https://mowl.readthedocs.io/en/v0.1.0/tutorials/embed.html#syntactic-embeddings) from mOWL's documentation.
