### ISSUE TITLE
Error during execution

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/opa2vec#4]
The run script fails for me with this error message:
```
***********Metadata Extraction ...***********

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Error grabbing Grapes -- [download failed: org.apache.httpcomponents#httpclient;4.5.1!httpclient.jar, download failed: org.apache.httpcomponents#httpcore;4.4.3!httpcore.jar]

java.lang.RuntimeException: Error grabbing Grapes -- [download failed: org.apache.httpcomponents#httpclient;4.5.1!httpclient.jar, download failed: org.apache.httpcomponents#httpcore;4.4.3!httpcore.jar]
```
In the end, there are no annotation properties processed and all I end up with is the set of axioms.

**Comment by debuos512** [comment]
I think this is an intermittent problem of grapes/maven being
down/overloaded - for me it worked

**Comment by leechuck** [comment]
Interesting. I think it would be good to include all the dependencies in the docker image @fzohrasmaili is preparing.

**Comment by fzohrasmaili** [comment]
The dependencies are now specified in more detail in the readme file. Will also take care of that once  the docker image is created .
