### ISSUE TITLE
To add a -o (--output) option for output directories

### ISSUE THREAD

**Issue by ChaseWLW** [bio-ontology-research-group/opa2vec#5]
It would be great that the users can specify a output directory for all the files to be stored, instead of in the same directory as opa2vec software (right now users have to keep multiple opa2vec or actively backup different outputs).

**Comment by fzohrasmaili** [comment]
I have decided to cleanup all intermediate files and only keep one ouptut file to avoid confusion and possible errors from running multiple times. What do you think ?

**Comment by ChaseWLW** [comment]
How about make available a --debug option and we only keep the intermediate files if we want to debug?

**Comment by fzohrasmaili** [comment]
Sure, that's even better!

**Comment by fzohrasmaili** [comment]
done !
