### ISSUE TITLE
Longer sentences broken down in axiomsorig.lst

### ISSUE THREAD

**Issue by ChaseWLW** [bio-ontology-research-group/opa2vec#7]
If you run ProcessOntology on phenomeNet, there would be long sentences broken into shorter segments. 

For example,
(PATO_0000001 and (has-modifier some PATO_0000460))) and (BFO_0000050 some 
(CHEBI_33567 and (BFO_0000050 some UBERON_0001088))))

**Comment by fzohrasmaili** [comment]
Have you used the latest code from GitHub ? Because I did replace all line breaks in axioms with a space.

**Comment by ChaseWLW** [comment]
Yes I missed that update. Let me close this.
