### ISSUE TITLE
Docker Version permissions

### ISSUE THREAD

**Issue by colemai** [bio-ontology-research-group/opa2vec#8]
I'm running docker but getting permission denied for accessing the associations file

Command:
```
docker run -v /home/Documents/thesis/opa-dat:/opt/data kaustborg/opa2vec
```

Error:
/opt/data/myassociations permission denied

**Comment by fzohrasmaili** [comment]
Have you tried running the command as sudo ? Also the association file and ontology file should be in your /home/Documents/thesis/opa-dat so that when you run the command above, they get transferred into the container

**Comment by colemai** [comment]
Thanks for your help! I pulled a fresh version of the code and ran it again, working perfectly
