### ISSUE TITLE
Requires entities arg

### ISSUE THREAD

**Issue by colemai** [bio-ontology-research-group/opa2vec#9]
If I run opa2vec without an entities argument it's supposed to default to giving me vectors for all entities

However at the moment it seems to require an entities file or else default to a nonexistent file and kick up an error

FileNotFoundError: [Errno 2] No such file or directory: 'finalclasses.lst'

**Comment by fzohrasmaili** [comment]
Thank you for your comment. Have you been using the latest version of the code shared ? Because this problem was occurring when the association file is empty but it has been solved in the getclasses.pl function recently

**Comment by colemai** [comment]
Excellent, thanks! Working
